import type { Metadata } from "next";
import {
  Covered_By_Your_Grace,
  Knewave,
  Lato,
  Nerko_One,
  Outfit,
  Space_Mono,
} from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Analytics } from "@vercel/analytics/next";

const lato = Lato({
  weight: ["300", "400", "700"],
  variable: "--font-lato",
  subsets: ["latin"],
});

const knewave = Knewave({
  weight: ["400"],
  variable: "--font-knewave",
  subsets: ["latin"],
});

const outfit = Outfit({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-outfit",
  subsets: ["latin"],
});

const space_mono = Space_Mono({
  weight: ["400", "700"],
  variable: "--font-spacemono",
  subsets: ["latin"],
});

const covered_by_your_grace = Covered_By_Your_Grace({
  weight: ["400"],
  variable: "--font-covered",
  subsets: ["latin"],
});

const nerko_one = Nerko_One({
  weight: ["400"],
  variable: "--font-nerko",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "samm bakerr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${knewave.variable} ${outfit.variable} ${space_mono.variable} ${covered_by_your_grace.variable} ${nerko_one.variable}`}
      >
        <div className="layout">
          <Header />
          <main> {children}</main>

          <Footer />
        </div>
        <Analytics />
      </body>
    </html>
  );
}
