import type { Metadata } from "next";
import { Knewave, Lato, Outfit } from "next/font/google";
import "./globals.css";
import SamBakerLogo from "./components/SamBakerLogo";
import Footer from "./components/Footer";

const lato = Lato({
  weight: ["300", "400", "700"],
  variable: "--font-lato",
  subsets: ["latin"],
});

const knewave = Knewave({
  weight: ["400"],
  variable: "--font-knewave",
  subsets: ["latin"],
});

const outfit = Outfit({
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-outfit",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "samm bakerr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${knewave.variable} ${outfit.variable} antialiased`}
      >
        <div className="layout">
          <SamBakerLogo />
          <main> {children}</main>
          <div className="footer">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
